"""Initial migration

Revision ID: d172b2e38a75
Revises: 2c7e80581cc7
Create Date: 2026-07-27 15:28:10.342367
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd172b2e38a75'
down_revision: Union[str, None] = '2c7e80581cc7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

